site_name: Estrutura projeto de dados

repo_name: cllaud99/estrutura_projetos_dados
repo_url: https://github.com/cllaud99/estrutura_projetos_dados

nav:
  - Home: index.md
  - API: api.md
plugins:
  - search
  - mkdocstrings:
      default_handler: python
